# Reference: https://docs.docker.com/reference/compose-file/
name: ai-chatbot

services:
  backend:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    container_name: backend
    command:
      - --host=0.0.0.0
      - --port=8000
      - --log-level=warning
      - --model=qwen2.5:latest
      - --ollama=http://localhost:11434
    env_file: .env
    hostname: backend

  frontend:
    build:
      args:
        VITE_APP_BASE_API_URL: /api
      context: .
      dockerfile: services/frontend/Dockerfile
    container_name: frontend
    ports:
      - 80:80
