name: Lint

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  autopep8:
    name: Run autopep8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Initialize environment
        working-directory: services/api
        run: pip install -r dev-requirements.txt

      - name: Run autopep8
        working-directory: services/api
        run: autopep8 --exit-code --diff -aaar .

  mypy:
    name: Run mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Initialize environment
        working-directory: services/api
        run: pip install -r dev-requirements.txt

      - name: Run mypy
        working-directory: services/api
        run: mypy .

  flake8:
    name: Run flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Initialize environment
        working-directory: services/api
        run: pip install -r dev-requirements.txt

      - name: Run flake8
        working-directory: services/api
        run: flake8 .

  eslint:
    name: Run eslint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.19"

      - name: Install dependencies
        working-directory: services/frontend
        run: npm install

      - name: Run eslint
        working-directory: services/frontend
        run: npx eslint .
